baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kane Le Blog'
theme = 'hugo-PaperMod'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Blogs'
    pageRef = '/blogs'
    weight = 20
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 30

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4